### ISSUE TITLE
Travis: update to container architecture

### ISSUE THREAD

**Issue by egeerardyn** [matlab2tikz/matlab2tikz#709]
We should upgrade our Travis configuration to use the container architecture as it is faster and I suspect the legacy architecture will disappear sometime in the future.

However, currently there currently is a roadblock: Travis currently only has Octave 3.2 approved for use (since that is included in Ubuntu PP 12.04LTS).

There are a few possible solutions:
 - [ ] wait for the upgrade to [Ubuntu 15.04 TT](https://github.com/travis-ci/travis-ci/milestones/Ubuntu%2014.04%20-%20Trusty%20Tahr) which has Octave 3.8.1 and have it [whitelisted](https://github.com/travis-ci/apt-package-whitelist);
 - [ ] wait for the [Octave PPA](https://github.com/travis-ci/apt-source-whitelist/issues/53) get whitelisted by Travis, which is probably sooner;
 - [ ] install Octave in a userland directory.

The former two, we don't have a lot of say in, the latter might be quite a bit harder to get to work.

More info on the [migration](http://docs.travis-ci.com/user/migrating-from-legacy/) and [apt](http://docs.travis-ci.com/user/apt/) is on the Travis website.

The `.travis.yml` file will probably become (assuming PPA approach; but obviously not tested):
```YAML
language: c++
sudo: false # use container
# command to install dependencies
addons:
  apt:
    sources:
      - octave/stable
    packages:
      - octave
script:
  - cd test && /usr/bin/octave -q --eval runMatlab2TikzTests.m
notifications:
  hipchat: f4c2c5f87adc85025545e5b59b3fbe@Matlab2tikz
```
